version: '3.9'

services:
  pdf-extraction-service:
    build:
      context: ./pdf-extraction-service
    container_name: pdf-extraction-service
    ports:
      - "5003:5003"

  generate-cards-service:
    build:
      context: ./generate-cards-service
    container_name: generate-cards-service
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  image-description-service:
    build:
      context: ./image-description-service
    container_name: image-description-service
    ports:
      - "5002:5002"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  pdf-analysis-service:
    build:
      context: ./pdf-analysis-service
    container_name: pdf-analysis-service
    ports:
      - "5004:5004"
    depends_on:
      - pdf-extraction-service
      - image-description-service
      - generate-cards-service