apiVersion: apps/v1
kind: Deployment
metadata:
  name: img-desc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: img-desc
  template:
    metadata:
      labels:
        app: img-desc
    spec:
      containers:
      - name: img-desc
        image: stackup7/img_desc_service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
