apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-extraction-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-extraction
  template:
    metadata:
      labels:
        app: pdf-extraction
    spec:
      containers:
      - name: pdf-extraction
        image: dhbw23jk/pdf_extraction_service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
