apiVersion: apps/v1
kind: Deployment
metadata:
  name: verwaltungs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verwaltungs
  template:
    metadata:
      labels:
        app: verwaltungs
    spec:
      containers:
      - name: verwaltungs
        image: stackup7/verwaltungs_service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
