openapi: '3.0.0'
info:
  title: PDF Analysis Service Central Control API
  description: API for analyzing PDF files, extracting content, describing images, and generating flashcards out of those
  version: '1.0'
servers:
  - url: /
paths:
  /analyse-pdf:
    post:
      summary: Analyze PDF and generate flashcards
      operationId: analysePdf
      requestBody:
        description: Base64 encoded PDF data
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - pdf
              properties:
                pdf:
                  type: string
                  format: base64
                  description: Base64 encoded PDF data
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  flashcards:
                    type: array
                    description: Generated flashcards from PDF content
                    items:
                      $ref: '#/components/schemas/Flashcard'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Flashcard:
      type: object
      properties:
        title:
          type: string
          description: Title of the flashcard
        front:
          type: string
          description: Front side of the flashcard (question/problem)
        back:
          type: string
          description: Back side of the flashcard (answer/solution)
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        details:
          type: string
          description: Additional error details