openapi: 3.0.0
info:
  title: PDF Extraction Service API
  version: "1.0.0"
  description: >
    Dieser Service empfängt eine PDF (als Base64-codierter String) über den Endpunkt `/pdf-extract`
    und extrahiert daraus den Inhalt als Markdown sowie ein Dictionary der enthaltenen Bilder.
    Die Antwort liefert den Markdown-Text und ein Dictionary, in dem jeder Bildname einem Base64-codierten Bild zugeordnet ist.
servers:
  - url: https://your-domain.com
paths:
  /pdf-extract:
    post:
      summary: Extrahiert den Inhalt einer PDF
      description: >
        Dieser Endpunkt nimmt eine PDF entgegen, extrahiert den Inhalt als Markdown und liefert zusätzlich
        ein Dictionary der Bilder zurück.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PdfExtractRequest'
      responses:
        '200':
          description: Erfolgreiche Extraktion der PDF
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PdfExtractResponse'
        '400':
          description: Ungültige Eingabe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    PdfExtractRequest:
      type: object
      properties:
        pdf:
          type: string
          format: base64
          description: Base64-codierte PDF-Datei
      required:
        - pdf
    PdfExtractResponse:
      type: object
      properties:
        markdown:
          type: string
          description: Markdown-Inhalt, extrahiert aus der PDF
        images:
          type: object
          description: Dictionary mit Bildnamen als Schlüssel und Base64-codierten Bildern als Werte
          additionalProperties:
            type: string
            format: base64
    Error:
      type: object
      properties:
        message:
          type: string
          description: Fehlermeldung
      required:
        - message
