openapi: '3.0.0'
info:
  title: Flashcard Generator API
  description: API for generating flashcards from markdown text
  version: '1.0'
servers:
  - url: /
paths:
  /generate_cards:
    post:
      summary: Generate flashcards from markdown text
      operationId: generateFlashcards
      requestBody:
        description: Markdown text to generate flashcards from
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - markdown_text
              properties:
                markdown_text:
                  type: string
                  description: The markdown text to generate flashcards from
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flashcard'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Flashcard:
      type: object
      properties:
        title:
          type: string
          description: Title of the flashcard
        front:
          type: string
          description: Front side of the flashcard (question/problem)
        back:
          type: string
          description: Back side of the flashcard (answer/solution)
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message